/* SCE CONFIDENTIAL
PhyreEngine(TM) Package 2.6.0
* Copyright (C) 2009 Sony Computer Entertainment Inc.
* All Rights Reserved.
*/
 
//
// パーティクル頂点シェーダの例
//

struct IN
{
	float4	ParticlePosition			: POSITION;
	float4	ParticleUVTileScaleOffset	: TEXCOORD1;
	float	ParticleLifetime			: TEXCOORD0;
};

struct OUT
{
	float4	clipSpace					: POSITION;
	float4	tc							: TEXCOORD0;
	float4	tcScale						: TEXCOORD1;
	float	psize						: PSIZE;
};

OUT main(
	in IN input,
	uniform float4x4 ModelView,
	uniform float4x4 ModelViewProj)
{
	OUT output;
	
	float4 position = float4(input.ParticlePosition.xyz, 1.0f);

	// ポイントサイズの計算
	if (input.ParticleLifetime <= 0.0f)
	{
		output.psize = 0.0f;
	}
	else
	{
		const float pointSize = 8192.0f;
		float4 eyeSpacePosition = mul(ModelView, position);
		output.psize = pointSize * sqrt(1.0f / (dot(eyeSpacePosition.xyz, eyeSpacePosition.xyz)));
	}

	// ポイントをclipSpaceに変換
	output.clipSpace = mul(ModelViewProj, position);

	output.tc = float4(0);
	output.tcScale = input.ParticleUVTileScaleOffset;

	return output;
}
